name: hichatbot
description: hichatbot app
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 5.0.0+5

#environment:
#  sdk: ">=2.18.6 <3.0.0"

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_markdown: ^0.6.15
  uuid: ^3.0.7
  #  http: ^0.13.5
  sp_util: ^2.0.3
  #  shared_preferences: ^2.0.20
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  dart_openai: ^2.0.1
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  rating_dialog: ^2.0.4
  lottie: ^2.3.1
  provider: ^6.0.5
  flutter_tts: ^3.7.0
  speech_to_text: ^6.1.1
  vibration: ^1.7.7
  animated_text_kit: ^4.2.2
  flutter_tex: ^4.0.3+4
  flutter_widget_from_html_core: ^0.10.1
  google_mobile_ads: ^2.4.0
  in_app_purchase: ^3.1.7
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.2.2
  firebase_core: ^2.5.0
  google_sign_in: ^6.0.1
  http: ^1.0.0
  in_app_purchase_android: ^0.3.0+5
  firebase_analytics: ^10.4.3
  in_app_review: ^2.0.6
  upgrader: ^6.5.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  flutter_dotenv: ^5.0.2
  change_app_package_name: ^1.1.0

dependency_overrides:
  markdown: ^7.0.0
  http: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
        - asset: fonts/Poppins-Regular.ttf
flutter_intl:
  enabled: true
flutter_icons:
  android: true
  ios: true
  image_path: "images/hichatboticon.png"